"heroes" {
	// <font color='#40cc66'>Ability</font>
	"npc_dota_hero_antimage" // Supported
	{
		"hero_name" "Astaroth"
		"lanes" {
			"general"
			{
				"overview" "<ul><li>An odd Hero, requires striking the opponent 7 consecutive times to truly get the most out of his skillset.</li>
				<li>High Magical, Physical and Pure DPS makes him very versatile as a carry.</li>
				<li>Farming capabilities are good with Overwhelm's AoE damage.</li>
				<li>Very very fragile.</li>
				<li>Small Mana pool and Health pool.</li>
				<li>Bad stat growth and base stats.</li></ul>"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "<ul><li>Black Insignia allows okay jungling.</li>
				<li>Otherwise he is not suited to this role.</li></ul>"
				"rating" "2"
			}
			"safelane"
			{
				"overview" "<ul><li>Powerful safelaner.</li>
				<li>Overwhelm offers good harrass.</li>
				<li>Pain Curse can secure kills.</li>
				<li>Especially weak to powerful offlaners such as Siegfried, Alexander, Vulcan or Tek.</li>
				<li>Can be easily zoned by dual lane combos, such as The Lich and Reus.</li></ul>"
				"rating" "4"
			}
			"offlane"
			{
				"overview" "<ul><li>Excellent harrass on Safelaner with Overwhelm and Pain Curse.</li>
				<li>A single proc of Black Insignia is enough to set up a kill.</li>
				<li>No escape.</li>
				<li>Very squishy.</li>
				<li>Difficult to sustain Mana.</li></ul>"
				"rating" "3"
			}
			"midlane"
			{
				"overview" "<ul><li>Melee, so midlane is difficult.</li>
				<li>Overwhelm offers good zoning and farming capabilities.</li>
				<li>Midlane towers are too close together to allow consistent Black Insignia procs.</li></ul>"
				"rating" "2"
			}
		}
	}
	"npc_dota_hero_axe"
	{
		"hero_name" "War"
		"lanes" {
			"general"
			{
				"overview" "War is a bit of a strange Hero, but powerful nonetheless in any circumstance given to him."
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_bane"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_bloodseeker" // Supported
	{
		"hero_name" "Bloodwarrior"
		"lanes" {
			"general"
			{
				"overview" "<ul><li>Powerful nuker.</li>
				<li>Difficult to kill thanks to his Ultimate, Blood Curse.</li>
				<li>Has excellent sustain in lane thanks to Grapple.</li>
				<li>Can quickly kill low enemies with great chase and damage.</li>"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "<ul><li>This is subpar from minute 0.</li>
				<li>Capable of sustaining thanks to Bloodmark, but Grapple does nearly nothing to creeps.</li>
				<li>Requires Mana regen of some kind to properly jungle.</li>
				<li>Possible with Iron Talon.</li>"
				"rating" "3"
			}
			"safelane"
			{
				"overview" "<ul><li>Does not need farm that much, but can snowball with it.</li>
				<li>Capable of harrassing the enemy offlaner quite easily.</li>"
				"rating" "3"
			}
			"offlane"
			{
				"overview" "<ul><li>Incredible sustain.</li>
				<li>Great harrass on the enemy safelaner.</li>
				<li>Excellent at making farming difficult.</li>
				<li>Difficult to kill thanks to Ultimate.</li>
				<li>Offlaning is Bloodwarrior's preferred role.</li>"
				"rating" "5"
			}
			"midlane"
			{
				"overview" "<ul><li>Similar to offlane.</li>
				<li>Capable of zoning out the enemy midlaner.</li>
				<li>Can dive with Ultimate.</li>"
				"rating" "4"
			}
		}
	}
	"npc_dota_hero_crystal_maiden"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_drow_ranger"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_earthshaker"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_juggernaut"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_mirana"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_nevermore"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_morphling"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_phantom_lancer"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_puck"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_pudge"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_razor"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_sand_king"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_storm_spirit"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_sven"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_tiny"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_vengefulspirit"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_windrunner"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_zuus"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_kunkka"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_lina"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_lich"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_lion"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_shadow_shaman"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_slardar"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_tidehunter"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_witch_doctor"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_riki"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_enigma"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_tinker" // Supported
	{
		"hero_name" "Tek"
		"lanes" {
			"general"
			{
				"overview" "<ul><li>Powerful Magical damage nuker.</li>
				<li>Extremely capable in 1v1 match-ups.</li>
				<li>Huge damage with Mosquito Missiles.</li>
				<li>Low cooldown spells.</li>
				<li>Hefty mana costs.</li>
				<li>Very fragile.</li>
				<li>Especially suited to <b>Midlane</b>, but not great at Offlane or Safe lane.</li></ul>"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "<ul><li>Surprisingly good at jungle thanks to Skycrack and Aerial Assault Mines.</li>
				<li>Still not a recommended lane, as he is very squishy and needs both gold and levels.</li>
				<li>Grants quick levels and could be okay if your preferred lane is taken or too dangerous.</li>
				<li>Buy Mana regen such as Soul Ring to properly utilise his skills.</li></ul>"
				"rating" "3"
			}
			"safelane"
			{
				"overview" "<ul><li>A bad lane for Tek.</li>
				<li>Most offlaners can deal with Tek easily, as his damage sources are either hard to hit (Skycrack) or deal less damage with more units (Mosquito Missiles).</li>
				<li>If you are forced into Safelane, Skycrack and to a lesser extent, his Aerial Assault Mines are decent regardless.</li></ul>"
				"rating" "3"
			}
			"offlane"
			{
				"overview" "<ul><li>A powerful offlaner, but fragile and difficult to harass with against a defensive support.</li>
				<li>Skycrack is the best ability to take in this lane, with a value point in Aerial Assault Mines to secure kills.</li></ul>"
				"rating" "4"
			}
			"midlane"
			{
				"overview" "<ul><li>This is Tek's lane.</li>
				<li>All of Tek's abilities are suited to Midlane.</li>
				<li>Capable of zoning the enemy with Skycrack and Mosquito Missiles.</li>
				<li>Aerial Assault Missiles is extremely good at securing first blood at the Runes and later on.</li></ul>"
				"rating" "5"
			}
		}
	}
	"npc_dota_hero_sniper" // Supported
	{
		"hero_name" "Hawkeye"
		"lanes" {
			"general"
			{
				"overview" "<ul><li>Glass cannon.</li>
				<li>Lane bully, focused on dealing damage early and midgame.</li>
				<li>May transition into a carry later on.</li>
				<li>Excellent in <b>Safelane</b> and <b>Offlane</b>, thanks to burst and attack range.</li></ul>"
				"rating" "5"
			}
			"jungle"
			{
				"overview" "<ul><li>Capable of dealing AoE damage with <font color='40cc66'>Detonator Dart</font>.</li>
				<li>Very fragile, not recommended.</li>
				<li>May be able to kill jungle creeps (very slowly) with <font color='40cc66'>Scattershot</font>.</li></ul>"
				"rating" "2"
			}
			"safelane"
			{
				"overview" "<ul><li>Very capable of farming with <font color='40cc66'>Scattershot</font> and <font color='40cc66'>Detonator Dart</font>.</li>
				<li>Base attack damage high enough to last hit efficiently.</li>
				<li>Attack point very low, allowing contesting of CS and harrassing of the Offlaner.</li>
				<li>Good escape thanks to <font color='40cc66'>Hit 'n' Run</font>.</li></ul>"
				"rating" "4"
			}
			"offlane"
			{
				"overview" "<ul><li>Powerful harrassment capabilities with <font color='40cc66'>Detonator Dart</font>.</li>
				<li>Great escape with <font color='40cc66'>Hit 'n' Run</font>.</li>
				<li><font color='40cc66'>Double Tap</font> has great kill potential when overlevelled.</li></ul>"
				"rating" "5"
			}
			"midlane"
			{
				"overview" "<ul><li>Great at harrassing from a distance.</li>
				<li>Difficult to take down thanks to <font color='40cc66'>Hit 'n' Run</font>.</li>
				<li>Early 6 means easy kills with <font color='40cc66'>Double Tap</font>.</li></ul>"
				"rating" "4"
			}
		}
	}
	"npc_dota_hero_necrolyte"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_warlock"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_beastmaster"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_queenofpain"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_venomancer"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_faceless_void"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_skeleton_king"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_death_prophet"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_phantom_assassin"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_pugna"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_templar_assassin"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_viper"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_luna"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_dragon_knight"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_dazzle"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_rattletrap"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_leshrac"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_furion"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_life_stealer"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_dark_seer"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_clinkz"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_omniknight"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_enchantress"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_huskar"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_night_stalker"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_broodmother"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_bounty_hunter"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_weaver"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_jakiro"
	{
		"hero_name" "Ouroboros"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_batrider"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_chen"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_spectre" // Supported
	{
		"hero_name" "Phantom"
		"lanes" {
			"general"
			{
				"overview" "<ul><li>Powerful lategame carry.</li>
				<li>Has anti-carry properties thanks to her Ultimate, Deathstrike.</li>
				<li>Incredible manfighting Hero thanks to Shadowstep and Deathstrike.</li>
				<li>Great farming capabilities with Nightmare.</li>
				<li>Has a reliable stun.</li>
				<li>Very very squishy.</li>
				<li>Easily shut down against high Magical burst or silences.</li>
				<li>Weak laner.</li></ul>"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "<ul><li>Early on, a bad lane for this Hero.</li>
				<li>Soul Wave allows an easier time, but uses up her small Mana pool.</li></ul>"
				"rating" "1"
			}
			"safelane"
			{
				"overview" "<ul><li>Phantom excels at Safelaning.</li>
				<li>Shadowstep is a powerful escape, and allows even the unwary to avoid ganks and dive towers.</li>
				<li>Soul Wave can focus a single target and secure kills.</li>
				<li>She is still very fragile.</li>
				<li>Be careful of diving offlaners with large Magical burst, like Bloodwarrior, or silencers, like Alexander.</li></ul>"
				"rating" "5"
			}
			"offlane"
			{
				"overview" "<ul><li>Dangerous in offlane, with good escape thanks to Shadowstep.</li>
				<li>Restrictive cooldowns.</li>
				<li>Soul Wave is great for harrassing, but uses her small Mana pool up.</li>
				<li>Not ideal but not bad.</li></ul>"
				"rating" "3"
			}
			"midlane"
			{
				"overview" "<ul><li>Capable of dealing a lot of damage to the enemy midlaner.</li>
				<li>Outclassed by heavy Magical burst cores like Tek, Crimson, Elementalist and Bloodwarrior.</li>
				<li>Shadowstep can be used to avoid ganks, but a single stun can make it useless.</li></ul>"
				"rating" "4"
			}
		}
	}
	"npc_dota_hero_doom_bringer"
	{
		"hero_name" "Alroth"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_ancient_apparition"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_ursa" // Supported
	{
		"hero_name" "Fury"
		"lanes" {
			"general"
			{
				"overview" "<ul><li>Dangerous Agi carry with extremely high attack damage when left to his own terms.</li>
				<li>Bloodsport can secure kills with its Damage Over Time.</li>
				<li>Has a slow in Terashock.</li>
				<li>Capable of manfighting nearly any other Hero with his Ultimate, Rampage.</li>
				<li>Even when dying, can inflict severe damage on the enemy team, thanks to his Ultimate, Rampage.</li></ul>"
			}
			"jungle"
			{
				"overview" "<ul><li>The bonus damage from Rend is enough to allow him to Jungle efficiently with Lifesteal.</li>
				<li>At least 2 points in Bloodsport will allow him to move off camps after hitting the creeps a few times.</li>
				<li>Can easily jungle with an Iron Talon.</li>
				<li>More suited to killing Heroes in lane, however.</li></ul>"
				"rating" "3"
			}
			"safelane"
			{
				"overview" "<ul><li>Suffers somewhat from bad attack point and base attack time.</li>
				<li>Capable of rotating into jungle at any point after level 3.</li>
				<li>Vulnerable to Magical burst, thanks to average Health pool.</li>
				<li>Can get kills on unwitting Offlaners.</li>
				<li>Right click is dangerous even against tankier enemies.</li></ul>"
				"rating" "4"
			}
			"offlane"
			{
				"overview" "<ul><li>Powerful and dangerous lane bully.</li>
				<li>Orb of Venom will allow him to easily kill slower enemies.</li>
				<li>Bloodsport means even 3 hits on an enemy can be devastating.</li></ul>"
				"rating" "4"
			}
			"midlane"
			{
				"overview" "<ul><li>Weak midlaner.</li>
				<li>Lacks both a ranged attack and chase before level 6/Blink Dagger.</li></ul>"
				"rating" "2"
			}
		}
	}
	"npc_dota_hero_spirit_breaker"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_gyrocopter"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_alchemist"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_invoker"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_silencer"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_obsidian_destroyer"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_lycan"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_brewmaster"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_shadow_demon"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_lone_druid"
	{
		"hero_name" "Artificer"
		"lanes" {
			"general"
			{
				"overview" "<ul><li>Extremely dangerous single target disabler/nuker.</li>
				<li>Powerful set of abilities.</li>
				<li>Reshape is an excellent set-up skill.</li>
				<li>Naturalise can force the enemy to retreat, and works well against Strength carries.</li></ul>"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "<ul><li>The Jungle is not recommended for this Hero.</li>
				<li>At level 1, his abilities are too expensive and do too little damage to properly Jungle.</li></ul>"
				"rating" "1"
			}
			"safelane"
			{
				"overview" "<ul><li>As a safelaner, Artificer is decently powerful.</li>
				<li>Able to easily farm, deny and harrass thanks to his Unmaking.</li>
				<li>Can deny cs simply by casting his Reshape on an enemy in mid-swing.</li>
				<li>Naturalise makes ganks from other lanes, and kills with the safelaning carry, much simpler.</li>
				<li>Recommended that he supports a core or carry.</li></ul>"
				"rating" "4"
			}
			"offlane"
			{
				"overview" "<ul><li>A dangerous lane for this Hero.</li>
				<li>Far too fragile to stay in lane.</li>
				<li>Has no sustain with his abilities.</li>
				<li>Capable of harrassing and saving himself, but this is very expensive.</li></ul>"
				"rating" "2"
			}
			"midlane"
			{
				"overview" "<ul><li>Ranged, so mid is possible.</li>
				<li>Will lose outright to stronger Magical damage opponents like Tek, Lightning and Elementalist, if his Reshape is mistimed.</li>
				<li>Capable of csing fairly easily with Unmaking.</li>
				<li>Very slow, so ganks may be difficult to deal with.</li></ul>"
				"rating" "3"
			}
		}
	}
	"npc_dota_hero_chaos_knight"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_meepo"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_treant"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_ogre_magi"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_undying"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_rubick"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_disruptor"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_nyx_assassin"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_naga_siren"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_keeper_of_the_light"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_wisp"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_visage"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_slark"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_medusa"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_troll_warlord"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_centaur"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_magnataur"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_shredder"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_bristleback"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_tusk"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_skywrath_mage"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_abaddon"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_elder_titan"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_legion_commander"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_ember_spirit"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_earth_spirit"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_abyssal_underlord"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_terrorblade"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_phoenix"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_techies"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_oracle"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_winter_wyvern"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
	"npc_dota_hero_arc_warden"
	{
		"hero_name" "None"
		"lanes" {
			"general"
			{
				"overview" "none"
				"rating" "0"
			}
			"jungle"
			{
				"overview" "none"
				"rating" "0"
			}
			"safelane"
			{
				"overview" "none"
				"rating" "0"
			}
			"offlane"
			{
				"overview" "none"
				"rating" "0"
			}
			"midlane"
			{
				"overview" "none"
				"rating" "0"
			}
		}
	}
}
